services:
  - type: web
    name: megamart-store
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
    staticPublishPath: ./dist
    autoDeploy: true
